theme: minima
encoding: UTF-8
title: "Money Fun with NerdWallet"
description: "Cool money tips every day!"
plugins:
  - jekyll-feed
feed:
  sources:
    - { url: "https://www.nerdwallet.com/blog/feed" }
    - { url: "https://feeds.megaphone.fm/newheights" }
